#!/bin/bash
#SBATCH -A SEE22001         # account name
#SBATCH -J p4_vectoradd     # job name
#SBATCH -o p4_vectoradd.%j  # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p small            # queue name
#SBATCH -t 00:00:30         # expected maximum runtime (hh:mm:ss)

date

./vectoradd_omp 10000000 56
./vectoradd_omp 100000000 56
./vectoradd_omp 1000000000 56

date
