#!/bin/bash
#SBATCH -A SEE22001         # account name
#SBATCH -J p1_collatz2       # job name
#SBATCH -o p1_collatz2.%j    # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p small            # queue name
#SBATCH -t 00:00:30         # expected maximum runtime (hh:mm:ss)

date

./collatz 9 1000000000

date
