#!/bin/bash
#SBATCH -A SEE22001         # account name
#SBATCH -J p5_vectoradd     # job name
#SBATCH -o p5_vectoradd.%j  # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p rtx-dev          # queue name
#SBATCH -t 00:00:30         # expected maximum runtime (hh:mm:ss)

date

./vectoradd_cuda 10000000
./vectoradd_cuda 100000000

date
