#!/bin/bash
#SBATCH -A SEE22001         # account name
#SBATCH -J p5_collatz       # job name
#SBATCH -o p5_collatz.%j    # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p rtx-dev          # queue name
#SBATCH -t 00:00:30         # expected maximum runtime (hh:mm:ss)

date

./collatz_cuda 5 10000
./collatz_cuda 5 20


date
