#!/bin/bash
#SBATCH -A SEE22001         # account name
#SBATCH -J p2_vectoradd2    # job name
#SBATCH -o p2_vectoradd2.%j # name of the output and error file
#SBATCH -N 2                # total number of nodes requested
#SBATCH -n 2                # total number of tasks requested
#SBATCH -p small            # queue name
#SBATCH -t 00:00:30         # expected maximum runtime (hh:mm:ss)

date

ibrun ./vectoradd_mpi 10000000
ibrun ./vectoradd_mpi 100000000
ibrun ./vectoradd_mpi 1000000000

date
