#!/bin/bash
#SBATCH -A SEE22001         # account name
#SBATCH -J p5_fractalT       # job name
#SBATCH -o p5_fractalT.%j    # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p rtx-dev          # queue name
#SBATCH -t 00:00:30         # expected maximum runtime (hh:mm:ss)

date

#./fractal_cuda 256 64
./fractal_cuda 2890000 60

date
