#!/bin/bash
#SBATCH -A SEE22001         # account name
#SBATCH -J p1_fractal       # job name
#SBATCH -o p1_fractal.%j    # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p small            # queue name
#SBATCH -t 00:01:00         # expected maximum runtime (hh:mm:ss)

date

./fractal 512 32
./fractal 512 64
./fractal 1024 32
./fractal 1024 64

date
