#!/bin/bash
#SBATCH -A SEE22001         # account name
#SBATCH -J p2_fractalT32     # job name
#SBATCH -o p2_fractalT32.%j  # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 32               # total number of tasks requested
#SBATCH -p small            # queue name
#SBATCH -t 00:00:30         # expected maximum runtime (hh:mm:ss)

date

ibrun ./fractal_mpi 256 32

date
