#!/bin/bash
#SBATCH -A SEE22001         # account name
#SBATCH -J p3_fractalT       # job name
#SBATCH -o p3_fractalT.%j    # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p small            # queue name
#SBATCH -t 00:01:00         # expected maximum runtime (hh:mm:ss)

date


./fractal_pthread 256 64 64

date
