#!/bin/bash
#SBATCH -A SEE22001         # account name
#SBATCH -J p2_collatzT1      # job name
#SBATCH -o p2_collatzT1.%j   # name of the output and error file
#SBATCH -N 1                # total number of nodes requested
#SBATCH -n 1                # total number of tasks requested
#SBATCH -p small            # queue name
#SBATCH -t 00:01:00         # expected maximum runtime (hh:mm:ss)

date

ibrun ./collatz_mpi 3 2000000

date
